Updated the build-scripts to build two versions of the release.
Signed-off-by: Filip Strömbäck <fstromback@gmail.com>

diff --git a/scripts/release-compile b/scripts/release-compile
--- a/scripts/release-compile
+++ b/scripts/release-compile
@@ -12,8 +12,13 @@ echo "core.info" > ${STORM_ROOT}/Compiler/COMPILER.version
 echo "$version" >> ${STORM_ROOT}/Compiler/COMPILER.version
 
 cd $STORM_ROOT
-mm release -ne || { echo "Compilation failed!"; exit 1; }
+
+# Seems to be more or less standard in Git bash at least. If we fail, we will just run the build
+# less efficiently, so it is not a big problem.
+mm release mps -ne || { echo "Compilation (mps) failed!"; exit 1; }
+mm release smm -ne || { echo "Compilation (smm) failed!"; exit 1; }
 
 echo "Done! Running test suite..."
-release/Test --all || { echo "Tests failed!"; exit 1; }
+release/Test_mps --all || { echo "Tests failed (mps)!"; exit 1; }
+release/Test_smm --all || { echo "Tests failed (smm)!"; exit 1; }
 echo "Success!"
diff --git a/scripts/release-full b/scripts/release-full
--- a/scripts/release-full
+++ b/scripts/release-full
@@ -18,9 +18,14 @@ fi
 
 release-compile || exit 1
 release-package zip || exit 1
-release-test zip || exit 1
+release-test $STORM_ROOT/release/storm_mps.zip || exit 1
+release-test $STORM_ROOT/release/storm_smm.zip || exit 1
 echo "All seems well, uploading the file..."
 hash=$(git rev-parse HEAD)
-cat $STORM_ROOT/release/storm.zip | ssh filip-www@fprg.se /home/filip-www/upload-storm.sh $version $hash
+function tar_it {
+    cd $STORM_ROOT/release
+    tar cz storm_mps.zip storm_smm.zip
+}
+tar_it | ssh filip-www@fprg.se /home/filip-www/upload-storm.sh $version $hash || { echo "Build failed on the server. Try again!"; exit 1; }
 
 echo "Finished! Remember to push tags!"
